### ISSUE TITLE
安装插件后启动App报错

### ISSUE THREAD

**Issue by rcho19** [ChanJianxun/cordova-icreate-amap-location#1]
安卓启动时报错：
Alert
 [ERROR]Error initializing Cordova:Class not found。

**Comment by ChanJianxun** [comment]
你的app是用cordova打包的吗？

**Comment by rcho19** [comment]
@ChanJianxun 是的，用的ionic3，这是的版本信息

cli packages:

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:

    cordova (Cordova CLI) : 8.0.0
local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2
System:

    Android SDK Tools : 26.1.1
    Node              : v7.6.0
    npm               : 4.1.2
    OS                : Windows 10

**Comment by ChanJianxun** [comment]
你在浏览器端运行你的程序吗?这个插件必须要在app端运行才行

**Comment by rcho19** [comment]
@ChanJianxun 额，是在真机上运行的，并且我发现在platforms\android\app\src\main\res\xml的config.xml中只加载了此插件的feature，其他插件都没有正常加载出来，所以提示了这个错误。
